### ISSUE TITLE
fast fine-tuning?

### ISSUE THREAD

**Issue by HobisPL** [rhasspy/piper#106]
I understand that your code uses the VITS code, right? Would it be possible to add fast fine-tuning, like in this repository: https://github.com/Plachtaa/VITS-fast-fine-tuning? Or is it a completely different repository?

Currently, I have trained three models, but they take quite a long time to train, as it requires around 6 hours of training to achieve a good voice. Also, the models mispronounce some words in the Polish language. I'm not sure if it's due to poor phonemization or the model itself.

**Comment by synesthesiam** [comment]
My VITS code has diverged quite a bit from the original, so I don't know if that approach will work. Some changes recently in Piper v1 may help your pronunciation issues with Polish (more phonemes added).

I'd also recommend using `--resume_from_checkpoint` to fine-tune one of the [pre-trained models](https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main). I have a couple Polish models available there.

**Comment by Maedeh-Nasr** [comment]
There isn't any checkpoint for the Persian (Farsi) language in the [pre-trained models](https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main). what should I do to fine-tune the Piper model in the Persian language?
