### ISSUE TITLE
Hungarian voice for Piper from mimic3

### ISSUE THREAD

**Issue by TheFocusDevHUN** [rhasspy/piper#110]
Greetings!

I have a quick question: 

Is it possible to port the following Hungarian model over to piper? It seems it uses the onnx format but stores phonemes and parameters differently.
https://github.com/MycroftAI/mimic3-voices/tree/master/voices/hu_HU/diana-majlinger_low

Do I need to retrain this model or it is enough to just take the parameters and convert it to the format that piper can understand?

**Comment by synesthesiam** [comment]
Two Hungarian voices are now available here: https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main/hu/hu_HU
