### ISSUE TITLE
Redirecting audio to `stdout` causes only the first line to be read.

### ISSUE THREAD

**Issue by broes5** [rhasspy/piper#112]
Running:
```sh
cat ~/Documents/2021/This\ Morning.txt|./piper --model en-gb-alan-low.onnx --output_file -|mpv --no-terminal ''-``
```
Should cause all the text in my file to be read immediately and not get saved to a file. Instead only the first line seems to be getting read.
I have to change it too:
```sh
cat ~/Documents/2021/This\ Morning.txt|./piper --model en-gb-alan-low.onnx --output_file /dev/stdout|mpv --no-terminal ''-``
```
To get all of the file to be read. I'm pretty sure the problem isn't the media player, since I've played with other speech synthases software using MPV that reads the whole file.

**Comment by synesthesiam** [comment]
Use `--output_raw` instead for this use case. This will stream the raw audio out as its generated. You need to match the same rate, etc. in the media player, for example:

```sh
echo 'This is a test. This is another test.' | piper -m en-us-lessac-medium.onnx --output_raw | aplay -r 22050 -c 1 -f S16_LE -t raw
```

**Comment by beqabeqa473** [comment]
I am just replacing \n with space and then writing it into wave file.

**Comment by broes5** [comment]
Okay. I guess it isn't really an issue anyway. There are multiple ways to get multi-line speech out of `piper`.

**Comment by broes5** [comment]
Oh, @synesthesiam your `aplay` rate argument is way too high.

**Comment by synesthesiam** [comment]
My example is using a medium quality voice, which has a sample rate of 22050Hz.
