### ISSUE TITLE
is piper support api access

### ISSUE THREAD

**Issue by ruiyi-star** [rhasspy/piper#114]
current use command piper is work well. but I want to use program to invoke piper, is piper support api access?

**Comment by synesthesiam** [comment]
Yes, you can see the C++ API here: https://github.com/rhasspy/piper/blob/master/src/cpp/piper.hpp
This needs to be turned into `libpiper.so` at some point and linked to from the main `piper` binary, but hasn't been done yet.

**Comment by ruiyi-star** [comment]
Can you supply some samples?  thanks in advance.

**Comment by ruiyi-star** [comment]
Now I know how to use C++ API.

**Comment by psych0v0yager** [comment]
Is there an update on this? Can Piper be used as a c++ API?
