### ISSUE TITLE
Use in Python

### ISSUE THREAD

**Issue by cslop3r** [rhasspy/piper#115]
Hi, is there a way to use piper inside a python script file instead of in a shell?

**Comment by beqabeqa473** [comment]
you could look at python_run directory. It is a bit out of date, but you could adapt libPiperPhonemize to be used in that script.

**Comment by cslop3r** [comment]
> you could look at python_run directory. It is a bit out of date, but you could adapt libPiperPhonemize to be used in that script.

Thanks for answering! Where do you see libPiperPhonemize?

**Comment by beqabeqa473** [comment]
look at another repo piper-phonemize in this organization

On 7/2/23, Nathan ***@***.***> wrote:
>> you could look at python_run directory. It is a bit out of date, but you
>> could adapt libPiperPhonemize to be used in that script.
>
> Thanks for answering! Where do you see libPiperPhonemize?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/rhasspy/piper/issues/115#issuecomment-1616771562
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by synesthesiam** [comment]
You should now be able to `pip install piper-tts` on Linux

**Comment by JakubCerven** [comment]
This worked for me, I essentially copied implementation from __main__.py

`
from piper import PiperVoice
import wave

voice = PiperVoice.load('your_local_model.onnx', config_path='your_local_config.onnx.json')

text = 'Example text'
with wave.open('test.wav', "wb") as wav_file:
    voice.synthesize(text, wav_file)
`

**Comment by synesthesiam** [comment]
The [piper-tts](http://pypi.org/project/piper-tts) Python package is now available

**Comment by BraianPita** [comment]
I am having issues installing the piper-tts python package in windows 10.

I tried
`pip install piper-tts`
on my venv, but I got this error:
```
pip install piper-tts
Collecting piper-tts
  Downloading piper_tts-1.2.0-py3-none-any.whl.metadata (776 bytes)
INFO: pip is looking at multiple versions of piper-tts to determine which version is compatible with other requirements. This could take a while.
  Downloading piper_tts-1.1.0-py3-none-any.whl.metadata (776 bytes)
ERROR: Cannot install piper-tts==1.1.0 and piper-tts==1.2.0 because these package versions have conflicting dependencies.

    piper-tts 1.2.0 depends on piper-phonemize~=1.1.0
    piper-tts 1.1.0 depends on piper-phonemize~=1.0.0

To fix this you could try to:
1. loosen the range of package versions you've specified

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

```
Then, I tried `pip install piper-tts==1.2.0`

And it gives this error:

```
pip install piper-phonemize
ERROR: Could not find a version that satisfies the requirement piper-phonemize (from versions: none)
ERROR: No matching distribution found for piper-phonemize
```
