### ISSUE TITLE
can't fix the size of onnx model

### ISSUE THREAD

**Issue by Xwmiss** [rhasspy/piper#119]
when I am fix the input size of the onnx model, but find the some ops did't have a fixed size. Such as the NonZero('/dp/flows.5/NonZero') in the onnx model, do you know why and how to fix it

**Comment by synesthesiam** [comment]
I don't know that specifically, but I'd guess it would be easier to fix the size in the export script: https://github.com/rhasspy/piper/blob/master/src/python/piper_train/export_onnx.py
