### ISSUE TITLE
zh_CN/huayan URL is invalid

### ISSUE THREAD

**Issue by cutefluffyfox** [rhasspy/piper#123]
Model card contains link to huayang repository, and [link](https://github.com/PlayVoice/HuaYan_TTS) provided on [Hugging face](https://huggingface.co/rhasspy/piper-voices/blob/main/zh/zh_CN/huayan/x_low/MODEL_CARD) is invalid.

**Comment by synesthesiam** [comment]
The dataset was apparently moved since I created the voice. Maybe @cgisky1980 knows where it is now?
