### ISSUE TITLE
Build from source problem

### ISSUE THREAD

**Issue by GIOVANNI-75** [rhasspy/piper#126]
impossible to build on x86_64, I tried to work around the problem but not succeeded, I think you should check the file hierarchy, some code calls dependencies in the wrong place and it creates a problem state that makes compilation impossible.
I also wanted to ask you if there was a way to ensure that the RAW output could be a buffer ready for use, I wanted to try it but I can't compile the code lol,
otherwise it's a good job bravo 👏🏻

**Comment by beqabeqa473** [comment]
I tried to build piper from sources without problems. Please provie more details.

**Comment by GIOVANNI-75** [comment]
ah, that's weird, even my colleague encountered build problems too, maybe I'm extracting the piper-phonemize in the wrong place, can you tell me more please?

**Comment by beqabeqa473** [comment]
could you provide more details so we can have a possibility to help.

On 7/4/23, GIOVANNI-75 ***@***.***> wrote:
> ah, that's weird, even my colleague encountered build problems too, maybe
> I'm extracting the piper-phonemize in the wrong place, can you tell me more
> please?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/rhasspy/piper/issues/126#issuecomment-1620587832
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by GIOVANNI-75** [comment]
![build-problem](https://github.com/rhasspy/piper/assets/58960396/d42bd093-ef6d-4e01-95af-0b29f46110d1)

**Comment by beqabeqa473** [comment]
Sorry, i won't be able to help this way.
Please copy plain text from the terminal and paste here, or maybe
someone else will be able to help you

On 7/4/23, GIOVANNI-75 ***@***.***> wrote:
> ![build-problem](https://github.com/rhasspy/piper/assets/58960396/d42bd093-ef6d-4e01-95af-0b29f46110d1)
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/rhasspy/piper/issues/126#issuecomment-1620629857
> You are receiving this because you commented.
>
> Message ID: ***@***.***>


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: ***@***.***
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by synesthesiam** [comment]
You should have a directory `piper/lib/Linux-x86_64/piper_phonemize` on a typical Intel/AMD machine.

**Comment by synesthesiam** [comment]
In the latest version of the Piper source, the CMake build has been reworked to be much better. Please try again and let me know if you still have problems.
