### ISSUE TITLE
usage of larynx in a python code

### ISSUE THREAD

**Issue by nfaraji2002** [rhasspy/piper#13]
Dear Michael,

I used the larynx in a python code as :
os.system("echo 'Welcome to the world of speech synthesis!' |   ./larynx --model ./larynx/en-us-blizzard_lessac-medium.onnx --output_file ./welcome.wav")

it works properly, however it just saves a .wav file to the specified folder. Then, I use "aplay" command for playing. 
when I modified the code as:
str='Welcome to the world of speech synthesis!'
os.system("echo $str |   ./larynx --model ./larynx/en-us-blizzard_lessac-medium.onnx --output_file ./welcome.wav")
It did not save anything. What is the wrong with the modification?

Is it possible that the usage of larynx is modified in such a way that it could directly accept a string as the input and play the result without saving the .wav file?
I mean a command like this:
./larynx --inputstr  'Welcome to the world of speech synthesis!' --model ./larynx/en-us-blizzard_lessac-medium.onnx

**Comment by synesthesiam** [comment]
Hi @nfaraji2002, yes it's possible to play the result without saving it as a WAV file. Here's one way:

```python
import subprocess

text = "Welcome to the world of speech synthesis!"
wav_bytes = subprocess.check_output(["larynx", "--model", "en-us-blizzard_lessac-medium.onnx", "--output_file", "-"], input=text.encode("utf-8")) 

subprocess.check_output(["aplay"], input=wav_bytes)
```

Calling `larynx` with `--output_file -` will write the WAV data to stdout instead of a file.
