### ISSUE TITLE
Wrong ISO code for Ukrania (UK vs UA)

### ISSUE THREAD

**Issue by set-soft** [rhasspy/piper#130]
The Ukrania country is code UA, not UK:

https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by mkiol** [comment]
My guess is that language code refers to [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

UA => Ukraine (country)
UK => Ukrainian (language)

**Comment by set-soft** [comment]
Yes, @mkiol the **uk_UK** is wrong (used by this project), it should be **uk_UA** (Ukrainian for Ukraine)

**Comment by synesthesiam** [comment]
This should be fixed now: https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0/uk

**Comment by set-soft** [comment]
The extra info in the JSON is very nice! Things are much simpler and the names in the native language looks beautiful:
![image](https://github.com/rhasspy/piper/assets/22823627/29e650a0-4190-4a5d-a6c2-8b9b28fecaae)
