### ISSUE TITLE
How do I write config json files for other pretrained VITS models?

### ISSUE THREAD

**Issue by dic1911** [rhasspy/piper#137]
As title, I'm trying to make a Japanese model work with piper by modifying json file for supported model(`en_US-lessac-medium.onnx.json`), but I keep getting the errors such as `Unknown phoneme table: ''` or `Invalid phoneme code XX` where XX is some number in `phoneme_id_map`

PS. [Here's the json](https://huggingface.co/spaces/Plachta/VITS-Umamusume-voice-synthesizer/blob/main/configs/uma_trilingual.json) for the model that I'm using if that matters

**Comment by rmcpantoja** [comment]
Hi @dic1911 ,
VITS configs don't work in piper, and it uses a different phonemizer and unicode conversion method, so it's best to train your datasets from scratch. Running piper_train.preprocess creates the configuration file.

**Comment by dic1911** [comment]
@rmcpantoja Okay, thanks for replying

**Comment by yakotoka** [comment]
@dic1911 Hi did you get it working in Japanese?
