### ISSUE TITLE
rate is wrong when piping to playback tool

### ISSUE THREAD

**Issue by EoceneMiacid** [rhasspy/piper#144]
Hi,

I'm piping piper's audio to pw-cat (pipewire playback tool) like so:

`echo "testing 1 2 3" | piper --model en_US-lessac-high.onnx --output_raw | pw-cat -p -`

This works, but the problem is that pw-cat plays it back too fast. The model should output at 22050, but I need to set pw-cat's playback rate to 11025 for it to play at normal rate, but then the quality is halved.

The same thing happens when I pipe it to pacat, even with the --fix-format and --fix-rate arguments.

Why does this happen?

**Comment by EoceneMiacid** [comment]
Reading the closed issues, I see  that using aplay like this:

`aplay -r 22050 -c 1 -f S16_LE -t raw`

plays it back at the correct rate.

**Comment by betaboon** [comment]
just ran into the same problem.

the reason is, the generated audio is _mono_, thus you have to run the following instead:
```
echo "testing 1 2 3" | piper --model en_US-joe-medium.onnx --output_raw | pw-cat -p --rate 
22050 --channels 1 -
```

to determine if the generated audio is mono or not:
```
$ echo "testing 1 2 3" | piper --model en_US-joe-medium.onnx --output_file welcome.wav

$ file welcome.wav 
welcome.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 22050 Hz
```
