### ISSUE TITLE
No silence between sentences

### ISSUE THREAD

**Issue by hubertlepicki** [rhasspy/piper#151]
When I run piper I get output that doesn't have any gaps between sentences.

```
echo "Hi there! How are things? There awas a princess and she lived in a castle. She was a pretty princess. A lot of knights wanted to steal her heart, but there was a big obstacle in their way: a dragon. The dragon was big and strong. He ate all of the knights. End." | ./piper --model /home/hubert/Pobrane/en_US-amy-medium.onnx --output_file hello.wav 
```

See attached output wav for result (zipped b/c GitHub won't allow me to upload Wav).

[hello.zip](https://github.com/rhasspy/piper/files/12174112/hello.zip)

I have tried passing `--silence_seconds 1`, this had no effect. Looking through source code, I found that maybe it's `--sentence_silence` https://github.com/rhasspy/piper/blob/c00ffd33340afa417d69760dc2c92c73dacef5c8/src/cpp/main.cpp#L453C24-L453C42 but it didn't work either.

This is actually not a problem for me, because I already divide the text into sentences before running it through piper, but it probably needs fixing

**Comment by hubertlepicki** [comment]
Actually I am testing it now and `--sentence_silence` works. So I think the only problem is that help screen lists is as `--silence_seconds`

**Comment by synesthesiam** [comment]
This has been fixed in 1.2.0. Additionally, you can now modify the silence after any phoneme (including punctuation like commas).

**Comment by SirNate0** [comment]
> Additionally, you can now modify the silence after any phoneme (including punctuation like commas).

How is this done?

**Comment by nicholascok** [comment]
> > Additionally, you can now modify the silence after any phoneme (including punctuation like commas).
> 
> How is this done?

They forgot to add this to the --help menu, but the option is `--phoneme-silence <phoneme> <seconds>`

**Comment by xlyralycanx** [comment]
> the option is `--phoneme-silence <phoneme> <seconds>`

My piper crashes with that argument. Trying to get it to spell words at a slower pace..

**Comment by Ishan5hrestha** [comment]
To anyone stuck, this woks fine
```
echo "Hello, all" | .\piper.exe -m .\en_GB-cori-high.onnx -c en_en_GB_cori_high_en_GB-cori-high.onnx.json --phoneme-silence , 0.2 --sentence-silence 1 -f test1.wav
```
