### ISSUE TITLE
No silence between sentences (Python)

### ISSUE THREAD

**Issue by DogeLord081** [rhasspy/piper#163]
Basically #151 but for Python not cpp. The new 1.2.0 version claims to have fixed it, but when I try to install and inference it just throws the same error as #157 even though I'm on Python 3.10.6. Otherwise, this TTS is so underrated and awesome though.

**Comment by DogeLord081** [comment]
Looks like the reason I cant install piper_phonemize is because im on windows. It worked fine on WSL2 Ubuntu. Is there a specific reason it cant be installed on windows?

**Comment by synesthesiam** [comment]
Yes, I need to set up GitHub actions to get Windows and macOS builds. I normally build on Linux with docker buildx. As far as I know, Microsoft and Apple haven't released docker build images.

**Comment by DogeLord081** [comment]
> Yes, I need to set up GitHub actions to get Windows and macOS builds. I normally build on Linux with docker buildx. As far as I know, Microsoft and Apple haven't released docker build images.

Oh alr cool. Me and another developer did get inference running on Windows with v1.0.0 and 1.1.0 with a build of espeak-ng-windows so I was hoping thered be a substitute or something. I guess for now I can do some WSL2 stuff. Do you have an estimated timeframe for when you can get piper_phonemize working on windows?

**Comment by synesthesiam** [comment]
I don't have a time estimate, unfortunately :/

**Comment by DogeLord081** [comment]
Ok np thanks for making this awesome TTS anyway!

**Comment by ftk7810** [comment]
Any updates on this? For Windows and MacOS ?

**Comment by tonperre** [comment]
Any updates on this matter ? I'm also on windows on this machine and I'd love to make it work ! 
Best
