### ISSUE TITLE
A way to NOT save every epoch checkpoint?

### ISSUE THREAD

**Issue by rtruszkowski** [rhasspy/piper#165]
I am using a Colab notebook to save my checkpoints and logs, and the checkpoints being saved for every epoch are causing a significant slowdown. I saw `every_n_epochs: Number of epochs between checkpoints.` in the docs, but that's buried somewhere deep in the code, and it's not obvious to me what I can change in my code to modify this. 

Ideally, only the best checkpoints would be saved, and not all, for every epoch. Am I doing something wrong?

**Comment by rmcpantoja** [comment]
Hi @rtruszkowski, 
Checkpoints are saved, yes, but delete any previously created checkpoint to leave just one checkpoint. Unfortunately, this causes Drive's trash to build up with models and needs to be emptied. I made a modification in my colab notebook so that only one model is saved. Check #88.

**Comment by rtruszkowski** [comment]
> 

Could you point me to the specific one? There are a few in there..

**Comment by synesthesiam** [comment]
Use `--checkpoint-epochs` with `python3 -m piper_train` to change the number of epochs between checkpoints.

**Comment by rtruszkowski** [comment]
What about keeping the checkpoints? I don't want the trainer to remove them?

**Comment by synesthesiam** [comment]
You'll need to modify the checkpoint options passed to PyTorch lightning for that.

**Comment by eschmidbauer** [comment]
im running into this same issue. I'd like to save the previous checkpoints instead of replacing them. Is there an easy way to accomplish this?
