### ISSUE TITLE
Using TPU with piper training

### ISSUE THREAD

**Issue by prevoste** [rhasspy/piper#169]
Hi, I am working through a tutorial on training a new model from an existing  .ckpt file using the ‘piper_train’ script. I am trying to run this on a Raspberry Pi 4 or I could use an Ubuntu laptop. I notice the accelerator parameter seems to have a ‘TPU’ option. Would the Coral Edge USB TPU work here, if so can any advise how to configure my Raspberry Pi environment?

Thanks Ernie

**Comment by marty1885** [comment]
No, the TPU option is for the cloud TPUs. Edge TPUs can only perform limited inference tasks.

See this SO question for more details:
https://stackoverflow.com/questions/60265752/coral-edge-tpu-can-use-it-for-training

**Comment by prevoste** [comment]
Hi Martin,

Thanks for the useful information.

Ernie
