### ISSUE TITLE
Unable to load fr_FR-upmc-medium

### ISSUE THREAD

**Issue by alexiri** [rhasspy/piper#179]
When trying to download the model for `fr_FR-upmc-medium` with `ensure_voice_exists`, I'm getting a `piper.download.VoiceNotFoundError` exception. Indeed, if I run the following:

```python
voices_info = get_voices()
print(sorted([x for x in voices_info.keys() if x.startswith("fr")]))
```

I get this output:
```
['fr_FR-gilles-low', 'fr_FR-mls_1840-low', 'fr_FR-siwis-low', 'fr_FR-siwis-medium']
```

which is in fact missing `fr_FR-upmc-medium`. I don't really understand this as I see an entry for this model in https://huggingface.co/rhasspy/piper-voices/blob/v1.0.0/voices.json. This is happening with version 1.1.0, I guess it will be resolved when 1.2 is published?

**Comment by Burnarz** [comment]
Still got the issue ?
I'm running piper with docker, but i could download this file, with the latest image.
I guess, you could still download it manually with a "wget url-of -the-voice" while on the right folder ;)
But honnestly ... siwis sounds better dispite the preview on the demo site ;)

**Comment by synesthesiam** [comment]
Try updating your add-on or Docker image again. All of the tags should be up to date now.

**Comment by alexiri** [comment]
Yes, now it works, thanks!
