### ISSUE TITLE
how extract onnx file from pt file ?

### ISSUE THREAD

**Issue by se8820726** [rhasspy/piper#21]
hi

i want to use this project on a gpu server

you says download a voice from [here](https://github.com/rhasspy/larynx2/releases/tag/v0.0.2)  and extract .onnx and .onnx.json files from it.
i choose the _generator-en-us_blizzard_lessac.tar.gz_ file. but there is not any onnx file in it and its content is this:
```
blizzard_lessac-medium.pt
blizzard_lessac-medium.pt.json
```

now how convert these files to onxx ?

I asked chatgpt and it said use this python code:

```
import torch
import onnx

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

model = torch.load('blizzard_lessac-medium.pt', map_location=device)
input_shape = (1, 80, 1000)  # Change the shape to match your model's input shape
input_names = ['input']
output_names = ['output']

# Export the model to ONNX format
onnx_model = onnx.export(model, args=(torch.zeros(input_shape),), f='blizzard_lessac-medium.onnx',
                         input_names=input_names, output_names=output_names)

onnx.save_as_json(onnx_model, 'blizzard_lessac-medium.onnx.json')

```
and this code give me this error:
`ModuleNotFoundError: No module named 'larynx_train'`

finally i didn't understand how can use your program !

**Comment by synesthesiam** [comment]
Please download this file instead: https://github.com/rhasspy/larynx2/releases/download/v0.0.2/voice-en-us_lessac.tar.gz

The .pt file is for use with Python only, whereas the onnx files are for C++ (and Python).
