### ISSUE TITLE
Add the "text to speech" and "tts" tag to the repo

### ISSUE THREAD

**Issue by sbsce** [rhasspy/piper#23]
I was spending a lot of time searching for a lightweight TTS library written in C++, and I couldn't find any. Primarily I was looking through this page to list all text to speech libraries written in C++: https://github.com/topics/text-to-speech?l=c%2B%2B

This repo isn't listed on that page because this repo does not have any tags assigned. For better discoverability, you should definitely add the fitting tags to this repo.

**Comment by synesthesiam** [comment]
Thanks for the idea! I've added the tags to the repo.
