### ISSUE TITLE
How fast is piper?

### ISSUE THREAD

**Issue by francqz31** [rhasspy/piper#235]
Hello Authors, 
I wanted to ask can piper run in real time ? how fast is it on an rtx3090 or any high end GPU?
I'm asking since I will use piper in a ai customer service experiment so it needs to be ran in human real time, if you know what I mean.

Thanks in advance!

**Comment by StoryHack** [comment]
How fast is can generate depends on the quiality of voice and the cpu, but yes. Even high quality voices generate much faster than realtime on my moderate system. I've never used the pip-installable version so that I could run inference via GPU, but that should be much faster than cpu.

**Comment by synesthesiam** [comment]
I have some benchmarks here: https://github.com/rhasspy/piper/issues/33

A lower "real-time factor" (RTF) is better, so even on a Raspberry Pi 4 you can get faster than realtime with low/medium quality models. On my AMD 5950X processor, even the high quality model runs over 12x faster than realtime (RTF = 0.082).
