### ISSUE TITLE
Streaming Audio on Windows

### ISSUE THREAD

**Issue by Sascha353** [rhasspy/piper#240]
I try to get the raw PMC audio stream on Windows to work but didn't succeed so far. As far as I can tell VLC should be capable to stream it with this parameters:

`echo "This sentence is spoken first. This sentence is synthesized while the first sentence is spoken." | piper --model en_GB-jenny_dioco-medium.onnx --output-raw | "C:\Program Files\VideoLAN\VLC\vlc.exe" --demux=rawaud --rawaud-channels=1 --rawaud-samplerate=22050 --rawaud-fourcc=s16l -`

or this without the GUI:

`echo "This sentence is spoken first. This sentence is synthesized while the first sentence is spoken." | piper --model en_GB-jenny_dioco-medium.onnx --output-raw | "C:\Program Files\VideoLAN\VLC\vlc.exe" -I dummy --demux=rawaud --rawaud-channels=1 --rawaud-samplerate=22050 --rawaud-fourcc=s16l -`

Unfortunately it's not working as expected. I can hear a faint voice during the playback but it's mostly white noise and crackle.

Any advice for VLC or any other option on Windows for audio streaming?

**Comment by Burnarz** [comment]
Know issue for Windows apparently see [https://github.com/rhasspy/piper/issues/213].
Just need to wait a new Windows release, or try to compile with the modifcations ^^
If you try, let me know, i'm interrested :D

**Comment by synesthesiam** [comment]
Please try the Windows version of the latest release: https://github.com/rhasspy/piper/releases/tag/2023.11.14-2
This includes (hopefully) a fix for Windows streaming.

**Comment by Sascha353** [comment]
It works, great! Thank you!

**Comment by jame25** [comment]
Just to add to this topic; sox.exe (Sound eXchange) can also be used to stream audio on Windows.

`piper --model en_GB-jenny_dioco-medium.onnx --output-raw < !temp_file! | sox,exe -t raw -b 16 -e signed-integer -r 22050 -c 1 - -t waveaudio pad 0 0.010 >NUL 2>&1`
