### ISSUE TITLE
Streaming the output (not waiting for whole generation to finish)

### ISSUE THREAD

**Issue by JohnAlcatraz** [rhasspy/piper#25]
Is it possible to use piper in a way that you don't need to "enter text, wait for the whole generation to finish, get a .wav. file, and then play the wav file", but instead get a "live" streaming output as it's being generated, so that playback can immediately start as soon as the first word, or the first sentence, has finished generating?

**Comment by synesthesiam** [comment]
Not out of the box, but it's possible with a little extra effort. Using a project like [pySBD](https://pypi.org/project/pysbd/), you can split a paragraph into sentences and feed each sentence into Piper as a separate line.

When you run `piper --output_dir /path/to/dir ...`, each line you send to Piper will be synthesized to a new WAV file in `/path/to/dir` and then the WAV file path will be printed back. So you can get "streaming" by:

1. Split text into sentences with `pySBD`
2. Run `piper` with `--output_dir` and access to stdin/stdout (e.g., `subprocess.Popen(..., stdin=PIPE, stdout=PIPE)`)
3. For each sentence:
    1. Write a line to the `piper` process
    2. Read a line back from the `piper` process and queue the WAV file to be played

**Comment by JohnAlcatraz** [comment]
Interesting, thanks for the info!

Would it be possible to also implement that natively so that it's possible out of the box, or is there some technical limitation that means it's not possible? Specifically also doing it word-by-word from some constantly streamed input buffer of text, and outputting into a constantly streamed output buffer of audio.

**Comment by synesthesiam** [comment]
Word-by-word isn't possible with the model without it sounding very bad. By it's possible to add the line-by-line streaming; the only limitation is my time :laughing:

**Comment by trunglebka** [comment]
My old college had an approach that applied to conventional architecture using intermediate representation like Mel. They first split text by sentences and generate mel for entire sentence, after that they will generate audio chunk by chunk for each mel chunk (say 0.4s). To generate high audio quality the input to decoder is prepended and appended with some neighbor mel.
The latency is really low.

**Comment by synesthesiam** [comment]
I have a sentence-by-sentence streaming option working locally. Not quite what your colleague proposed, more like:

1. Split text into sentences
2. As each sentence is being synthesized into audio, play the previous sentence(s)

Since the RTF is < 1, this means you will eventually be ahead and get audio much faster than before.
Unfortunately, this has required patching `espeak-ng` to allow me to figure out when it's reached the end of a sentence. But it's working so far! Just need some more testing before I push it up :slightly_smiling_face:

**Comment by dtx525942103** [comment]
https://github.com/PlayVoice/vits_chinese/blob/master/models.py#L894~970

Can this be applied? @synesthesiam

**Comment by synesthesiam** [comment]
In the latest Piper, I now have a streaming option:

```sh
echo "<long text>" | piper -m <voice> --output_raw | aplay -r 22050 -c 1 -f S16_LE -t raw
```

Make sure to set your sample rate appropriately for your voice.

@dtx525942103 Not sure, I will have to give it a try. Thanks!

**Comment by jaredhagel** [comment]
Great project! Thanks for releasing this as open source. The hardware we'd be interested to run this on has similar performance to Raspberry Pi 4, and even with this streaming change the delay is noticeable. For example, generating audio for the following text takes about 100 seconds which is a problem for us. I'm not sure if it's possible reducing this delay further, I just thought I'd point out this issue.

"Senior citizens can ride for 25 cents from 9 am to 3 pm on weekdays and free all weekend"

**Comment by jaredhagel** [comment]
voice-en-us-libritts-high.tar.gz taken from https://github.com/rhasspy/piper/releases/tag/v0.0.2

**Comment by synesthesiam** [comment]
Part of the time may be just loading the model. If you keep the piper process open, you can get much faster times if you synthesize more than one utterance: https://github.com/rhasspy/rhasspy3/blob/master/programs/tts/piper/bin/piper_server.py
I get a time of 4 seconds for the text you posted with the same lessac low voice if the model is already loaded.

**Comment by jaredhagel** [comment]
Good to know thank you Michael. It seems our hardware is slower than the Raspberry Pi 4 - we got this down to 10 seconds with your suggestion. Unfortunately even 4 seconds is too long for our requirements though, but it is a big improvement from 100 seconds!

**Comment by jianliu-ml** [comment]
> Part of the time may be just loading the model. If you keep the piper process open, you can get much faster times if you synthesize more than one utterance: https://github.com/rhasspy/rhasspy3/blob/master/programs/tts/piper/bin/piper_server.py I get a time of 4 seconds for the text you posted with the same lessac low voice if the model is already loaded.

Hi, does the server always generate a wav file? can we have a server performing streaming output like the `echo "<long text>" | piper -m <voice> --output_raw | aplay -r 22050 -c 1 -f S16_LE -t raw`?

**Comment by mush42** [comment]
@synesthesiam 

When using Piper with screen readers you get vastly varying levels of responsiveness based on the length of the text sent to Piper. This could be resolved via implementing streaming model output.

So, is there any way to (via shared memory or otherwise ) to get audio samples as they are being generated by `onnxruntime`?

Best

**Comment by synesthesiam** [comment]
@mush42 The VITS model under Piper isn't built for streaming, unfortunately. It operates on entire utterances, which can be small (clauses) but will only sound good if the voice was trained on them.
Piper can at least split paragraphs into sentences and stream the audio as soon as each sentence is ready.
