### ISSUE TITLE
Request change in "piper" TAR file naming

### ISSUE THREAD

**Issue by gvimlag** [rhasspy/piper#259]
REQUEST:
You've recently changed the naming convention of the piper tar files.
From: piper_<amd64/arm64/armv7>.tar.gz
To: piper_linux_<x64/aarch64/armv7>.tar.gz

To be consistent with the linux system variable "$HOSTTYPE", "x64" should be "x86_64".
Instead of: piper_linux_<x64/aarch64/armv7>.tar.gz
Please use: piper_linux_<x86_64/aarch64/armv7>.tar.gz

Following the linux system variable "$HOSTTYPE" convention simplifies writing download scripts for the user.
Example:
wget https://github.com/rhasspy/piper/releases/download/"$PIPER_VERSION"/piper_linux_"$HOSTTYPE".tar.gz

Thank you.

**Comment by csukuangfj** [comment]
![Screenshot 2023-10-31 at 10 21 30](https://github.com/rhasspy/piper/assets/5284924/8f8917c5-511f-4e70-9a0f-e344c84043e6)

**Comment by csukuangfj** [comment]
Microsoft is using x64 for linux, instead of x86_64.

**Comment by gvimlag** [comment]
Microsoft is dominant in widows, not linux.
In most linux systems, x86_64 is the value of the system variable.
I'm requesting a linux name (x86_64) in a linux tar file (example:  piper_linux_x86_64.tar.gz) .
(It would also make sense to use a windows name in a windows tar file.  I'm requesting consistency.)

**Comment by synesthesiam** [comment]
Changed in the latest release: https://github.com/rhasspy/piper/releases/tag/2023.11.14-2
