### ISSUE TITLE
multiple languages at the same time

### ISSUE THREAD

**Issue by jjsarton** [rhasspy/piper#26]
I have make a little test with speech-dispatcher, I have used the generic modules.
The purpose was to test if I can send few German, French, and English text lines via sdp-say. The text file is multilingual and
use the syntax "!-!SET SELF LANGUAGE xx" before the few words of the next line.
This worked, but between the output of text with another language, there is noise. Is it possible to eliminate this?
The French pronunciation is better as for larynx or mimic3, but there are some little problems with "liaisons"

**Comment by synesthesiam** [comment]
How are you calling out to piper from speech-dispatcher?
