### ISSUE TITLE
Linux releases contain only x64 build

### ISSUE THREAD

**Issue by PeterHagen** [rhasspy/piper#263]
I think the Github build script adds the x64 code to aarch64 and armv7 releases. I copied all 3 linux releases to different folders and get the same message on running it in Docker (on macOS):

```bash
root@602a0ba1c943:/data/aarch64/piper# ./piper
OrbStack ERROR: Dynamic loader not found: /lib64/ld-linux-x86-64.so.2

This usually means that you're running an x86 program on an arm64 OS without multi-arch libraries.
```

Checking with the file command gives me this:

```bash
root@602a0ba1c943:/data/aarch64/piper# file ./piper
./piper: ELF 64-bit LSB pie executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4b66130bd84000a8da56440929f82b181fcad608, for GNU/Linux 3.2.0, not stripped
```

I never used GitHub builds before, but as I read the `main.yml` script, I personally think it copies the same binary for all 3 platforms:

```
      - name: package
        run: |
          cd _install && \
          tar -czf piper_linux_${{ matrix.arch }}.tar.gz piper/
```

There is no `{{ matrix.arch }}` specified on the build command. I have no idea how to add this, to be honest.

**Comment by synesthesiam** [comment]
Fixed in the latest release: https://github.com/rhasspy/piper/releases/tag/2023.11.14-2
Apparently Github runners don't actually run using the architecture you specify :/
