### ISSUE TITLE
Terminate called after throwing an instance of 'std::runtime_error'   what():  Model config doesn't exist

### ISSUE THREAD

**Issue by sciretta** [rhasspy/piper#277]
I am trying to execute the command 
`echo 'Probando texto en espanol' | ./piper --model es_MX-ald-medium.onnx --output_file welcome.wav`

inside the folder piper, which has this content (uncompressed from `piper_linux_x86_64.tar.gz`)

.
..
espeak-ng
espeak-ng-data
libespeak-ng.so
libespeak-ng.so.1
libespeak-ng.so.1.52.0.1
libonnxruntime.so
libonnxruntime.so.1.14.1
libpiper_phonemize.so
libpiper_phonemize.so.1
libpiper_phonemize.so.1.2.0
libtashkeel_model.ort
piper
piper_phonemize
pkgconfig

also I added my model among other related files

es_es_MX_ald_medium_es_MX-ald-medium.onnx.json \n
es_es_MX_ald_medium_MODEL_CARD
es_MX-ald-medium.onnx

inside the folder piper as well, 

.
..
es_es_MX_ald_medium_es_MX-ald-medium.onnx.json
es_es_MX_ald_medium_MODEL_CARD
es_MX-ald-medium.onnx
espeak-ng
espeak-ng-data
libespeak-ng.so
libespeak-ng.so.1
libespeak-ng.so.1.52.0.1
libonnxruntime.so
libonnxruntime.so.1.14.1
libpiper_phonemize.so
libpiper_phonemize.so.1
libpiper_phonemize.so.1.2.0
libtashkeel_model.ort
piper
piper_phonemize
pkgconfig

but when I try to run the command above I get this error

`terminate called after throwing an instance of 'std::runtime_error'
  what():  Model config doesn't exist
Aborted (core dumped)`

what am I doing wrong?

**Comment by sciretta** [comment]
I am using last version

**Comment by ye110wd** [comment]
I noticed one problem. There could be more.
es_es_MX_ald_medium_es_MX-ald-medium.onnx.json \n
es_MX-ald-medium.onnx

./piper --help

> path to model config file (**default: model path + .json**)

so filenames should be.
es_MX-ald-medium.onnx.json 
es_MX-ald-medium.onnx

**Comment by sciretta** [comment]
yes @ye110wd  that was the problem, I tried using the same name for the .onnx and .onnx.json files and it worked, thanks
