### ISSUE TITLE
Portugal pt-PT language does not work 

### ISSUE THREAD

**Issue by JeditPro** [rhasspy/piper#282]
Here, Brazil pt-BR language works correctly in Windows 10. But Portugal pt-PT language does not work in the latest version. When I try to use it, nothing happens.

https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0/pt/pt_PT/tug%C3%A3o/medium

Thank you very much for your excellent work.

**Comment by 520Pig520** [comment]
i tried the tugao model, and it works.
not the best voice ever, but works
https://huggingface.co/spaces/k2-fsa/text-to-speech
maybe your code is wrong.

**Comment by synesthesiam** [comment]
@vluz You may have your Windows terminal set to a non-UTF8 encoding

**Comment by JeditPro** [comment]
@vluz 
Your procedure worked correctly here. Thank you very much.

@synesthesiam 
Yes, my Windows terminal is seted to a UTF8 encoding. I use this code in CMD
REM change CHCP to UTF-8
CHCP 65001
CLS
