### ISSUE TITLE
cannot fine tune from libritts checkpoint

### ISSUE THREAD

**Issue by eschmidbauer** [rhasspy/piper#30]
Hi,
I downloaded the pretrained model from [google drive](https://drive.google.com/drive/u/0/folders/1e1tBE1GywXCY2c1RmfPl95Q5w0YBc0C8)

i'm attempting to fine-tune but getting an error. Here is my FT command (this works with ljspeech pretrained model btw)
```
python -m piper_train \
    --resume_from_checkpoint 'checkpoints/libritts/high/epoch=418-step=1582960.ckpt' \
    --accelerator 'gpu' \
    --devices 1 \
    --batch-size 32 \
    --validation-split 0.01 \
    --num-test-examples 0 \
    --max-phoneme-ids 400 \
    --max_epochs 10000 \
    --dataset-dir training_24000 \
    --checkpoint-epochs 1  \
    --quality high
```

Here is the error:
```
Restoring states from the checkpoint path at checkpoints/libritts/high/epoch=418-step=1582960.ckpt
DEBUG:fsspec.local:open file: /home/admin/piper/src/python/checkpoints/libritts/high/epoch=418-step=1582960.ckpt
Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/admin/piper/src/python/piper_train/__main__.py", line 95, in <module>
    main()
  File "/home/admin/piper/src/python/piper_train/__main__.py", line 88, in main
    trainer.fit(model)
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1056, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1000, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 261, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 363, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/admin/miniconda3/envs/piper/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VitsModel:
	Unexpected key(s) in state_dict: "model_g.emb_g.weight", "model_g.dec.cond.weight", "model_g.dec.cond.bias", "model_g.enc_q.enc.cond_layer.bias", "model_g.enc_q.enc.cond_layer.weight_g", "model_g.enc_q.enc.cond_layer.weight_v", "model_g.flow.flows.0.enc.cond_layer.bias", "model_g.flow.flows.0.enc.cond_layer.weight_g", "model_g.flow.flows.0.enc.cond_layer.weight_v", "model_g.flow.flows.2.enc.cond_layer.bias", "model_g.flow.flows.2.enc.cond_layer.weight_g", "model_g.flow.flows.2.enc.cond_layer.weight_v", "model_g.flow.flows.4.enc.cond_layer.bias", "model_g.flow.flows.4.enc.cond_layer.weight_g", "model_g.flow.flows.4.enc.cond_layer.weight_v", "model_g.flow.flows.6.enc.cond_layer.bias", "model_g.flow.flows.6.enc.cond_layer.weight_g", "model_g.flow.flows.6.enc.cond_layer.weight_v", "model_g.dp.cond.weight", "model_g.dp.cond.bias".

```

**Comment by eschmidbauer** [comment]
interestingly this same command works with the `ryan` "high quality" checkpoint
```--resume_from_checkpoint 'checkpoints/ryan/high/epoch=4049-step=2826900.ckpt'```

**Comment by synesthesiam** [comment]
LibriTTS is a multi-speaker model, so it needs a dataset with multiple speakers (or at least with speaker ids).

**Comment by eschmidbauer** [comment]
that makes sense, I will try out a multi-speaker dataset and update here. Thanks!

**Comment by eschmidbauer** [comment]
looks like i needed a dataset with same number of speakers, 904 😮

**Comment by synesthesiam** [comment]
Not really, you just need `num_speakers` set to 904. You can still fine tune with only a single speaker.

**Comment by eschmidbauer** [comment]
Where / how do I set the num speaker value?

**Comment by synesthesiam** [comment]
Just edit the `config.json` in your dataset's directory after you run the preprocessing step.

**Comment by Oeathus** [comment]
> interestingly this same command works with the `ryan` "high quality" checkpoint `--resume_from_checkpoint 'checkpoints/ryan/high/epoch=4049-step=2826900.ckpt'`

Where did you find that ckpt? I've been pulling my hair out for hours trying to find even one ckpt for any vits model, it's driving me crazy and there doesn't seem to be any way that I can find to convert any kind of model to ckpt. I feel like I'm losing my mind a little bit.

**Comment by synesthesiam** [comment]
I have some available here: https://drive.google.com/drive/folders/1Hd_dP9BpDYbi1enRDEMIN34W1nfIgmp6?usp=sharing

The problem is they're pretty large, so I can't host a lot without running out of space. You can't convert from an ONNX model back into a checkpoint because most of the necessary information is gone (which is why the ONNX model is so much smaller). Specifically, the "discriminator" part of the checkpoint is only used during training, and is discarded when exporting to ONNX.

**Comment by Oeathus** [comment]
Thank you!! That makes a lot more sense and explains why I was struggling. I appreciate you hosting these, they're very helpful!! I've been swinging around some of those Large Language Models and have also run into storage limitations, [Hugging Face](https://huggingface.co/) has been letting me push up 30+GB repos so I can delete them from my hard drive, I don't know if that would be applicable for you as I think the repos have to be public (I can see not wanting voice clones being public), in any case, Thank you!!!

**Comment by Graylington** [comment]
> Just edit the `config.json` in your dataset's directory after you run the preprocessing step.

Where can I find config.json in the colab?

**Comment by thewh1teagle** [comment]
> Not really, you just need `num_speakers` set to 904. You can still fine tune with only a single speaker.

Besides setting the right num_speakers value, do we have to set also speaker_id in dataset.jsonl?

I tried that, I set the speaker_id to some existing one but then all the voices sounds the same after short training
