### ISSUE TITLE
Is there a way to use this in python?

### ISSUE THREAD

**Issue by fivestones** [rhasspy/piper#31]
I see on the readme.md about running this in python, but the example given in the end just uses a bash script which runs `python3 -m piper "$@"` at the end. And in the scr/python_run directory I ran the scripts/setup.sh, got that running, and then I can do `python` and then `>>>import piper` which works. But from there, what do I do to use the imported piper?

(Mostly unrelated: also, do you realize that running it like this makes it the py'd piper? ha! :-) I'm sure you already got that joke and maybe that had something to do with the name change from larynx 2?)

**Comment by synesthesiam** [comment]
I haven't had time to wrap this up into a proper `piper` package, but you can look at `__main__.py` in `src/python_run` to see how it imports and uses Piper.

**Comment by synesthesiam** [comment]
This is now wrapped up in the [piper-tts](https://pypi.org/project/piper-tts/) Python package.
