### ISSUE TITLE
Training Notebook - "warning: audio amplitude out of range, auto clipped"

### ISSUE THREAD

**Issue by MooTheCow** [rhasspy/piper#310]
Hi, recently I've been getting errors in the logs:

Epoch: 2170. Steps: 1355648
**warning: audio amplitude out of range, auto clipped.**
DEBUG:fsspec.local:open file: /content/drive/MyDrive/colab/piper/Test/lightning_logs/version_0/checkpoints/last.ckpt

This is for the same data set that I used before without getting those errors.
I'm not sure if this is affecting the final model, and what I need to do to the source audio to stop it.

**Comment by rmcpantoja** [comment]
Hi @MooTheCow, 
Those aren't errors, they are simple warnings when adding audios to tensorboard. Just ignore them, unless the audio on the tensorboard sounds bad and doesn't improve during training. If that is the case, stop it. Otherwise, you should not worry.

**Comment by MooTheCow** [comment]
OK, thanks!
