### ISSUE TITLE
Is Piper for short prompts only or can it be used for longer texts?

### ISSUE THREAD

**Issue by Kentoseth** [rhasspy/piper#312]
It looks like Piper is being created for Home Assistant type of technology, but I found 1 of your models trickled into a TTS tool I use:

https://github.com/mkiol/dsnote

Piper seems like the simplest tool for training a voice model to do TTS, but I am primarily seeking to create a dataset to use my voice for audio-books (transcriptions per chapter).

The [Jordanian Arabic model](https://huggingface.co/rhasspy/piper-voices/tree/main/ar/ar_JO/kareem/medium/) I tested out was able to read a few lines of text mostly accurately, but could the Piper training achieve the same level of accuracy when converting a few pages of text to audio?

**Comment by suppcuti** [comment]
I use this code for my auto reader you can use it too

$files = Get-ChildItem -Path "./your-dir" -Filter *.txt
foreach ($file in $files) {
    $name = $file.basename.Replace(" ", "")
    $output = "youroutput-dir/$name.wav"
    cat $file.FullName | ./piper.exe --model "your-model-url" --output_file $output
}

**Comment by Kentoseth** [comment]
> I use this code for my auto reader you can use it too
> 
> $files = Get-ChildItem -Path "./your-dir" -Filter *.txt foreach ($file in $files) { $name = $file.basename.Replace(" ", "") $output = "youroutput-dir/$name.wav" cat $file.FullName | ./piper.exe --model "your-model-url" --output_file $output }

Thanks for your reply.

I can mostly understand what your Shell code is doing, but I am unsure how it is relevant to the thread?

Can you share more info?

Thanks,

**Comment by C-Loftus** [comment]
Yeah Piper works well for audiobooks in my case. It is not perfect but I listen with 2x speed anyways and once sped up it sounds quite good. I don't see any reason why it wouldn't work

**Comment by suppcuti** [comment]
> cat "path to txt" | ./piper.exe --model "your-model-url" --output_file $output
yeah you just need this for long promt, sr
