### ISSUE TITLE
Preprocessing error when using language en-gb

### ISSUE THREAD

**Issue by Graylington** [rhasspy/piper#316]
When preprocessing everything works fine if I use "--language en-us", however when I try using "--language en-gb" I get the follow error:
`RuntimeError: Failed to set eSpeak-ng voice`

**Comment by jereskuta** [comment]
looking at eSpeak-ng documentation, en is british english and en-us is american english.

**Comment by Graylington** [comment]
> looking at eSpeak-ng documentation, en is british english and en-us is american english.

That's right, but why can't I use en-gb?

**Comment by jereskuta** [comment]
because en-gb is not a thing. you should use en if you want british english.

**Comment by Graylington** [comment]
> because en-gb is not a thing. you should use en if you want british english.

Oh, thanks!
