### ISSUE TITLE
ONNX model runtime

### ISSUE THREAD

**Issue by erogol** [rhasspy/piper#33]
Hey, do you have any runtime comparisons between the ONNX and Pytorch models? I wonder if it is worth trying for 🐸 models if you don't mind.

**Comment by synesthesiam** [comment]
Hi Eren :wave: 

I ran some benchmarks today, and I can confirm that ONNX is definitely faster. I tested 2 systems and 3 versions of a single speaker model. Here's the data:

| System | Framework | Quality | RTF (avg) |
|--------|-----------|---------|-----------|
| Rpi4   | PyTorch   | Low     | 0.819     |
| Rpi4   | Onnx      | Low     | 0.494     |
| Rpi4   | PyTorch   | Med     | 1.255     |
| Rpi4   | Onnx      | Med     | 0.803     |
| Rpi4   | PyTorch   | High    | 8.081     |
| Rpi4   | Onnx      | High    | 5.307     |
| 5950x  | PyTorch   | Low     | 0.032     |
| 5950x  | Onnx      | Low     | 0.019     |
| 5950x  | PyTorch   | Med     | 0.046     |
| 5950x  | Onnx      | Med     | 0.030     |
| 5950x  | PyTorch   | High    | 0.167     |
| 5950x  | Onnx      | High    | 0.082     |


I tested on a Raspberry Pi 4 with 4GB of RAM, and an AMD Ryzen 9 5950X with 64GB of RAM (latest torch 1.x and onnxruntime). On average, it seems the Onnx model has a 1.5-2x better RTF across the various model sizes. On the 5950x, you'd barely notice the difference but it's pretty pronounced on the Pi 4. 

For fun, I tried Torchscript versions of the models too, but they were over 10x slower so I didn't include them in the table.

**Comment by erogol** [comment]
Cool! Thanks for sharing and going through this. What was the torch version btw?

**Comment by synesthesiam** [comment]
Torch 2.0.0 on the 5950x, but I had to fall back to 1.13.1 on the Pi 4 because I was getting "illegal instruction" errors. I'm on Python 3.9, so that may be the problem.

**Comment by trunglebka** [comment]
I've run Piper with onnxruntime TensorrtExecutionProvider the speed is crazy it can generate 25s audio in just 90ms (RTF=0.0036 compared with RTF ~0.01 of CudaExecutionProvider on RTX 1660) but this option very unstable, sometimes it takes 10 minutes, sometime warning error.
Batching is not a good option though since we need to run Piper at sentence level, but the lengths between sentences vary greatly

**Comment by tkyin17** [comment]
> Hi Eren 👋
> 
> I ran some benchmarks today, and I can confirm that ONNX is definitely faster. I tested 2 systems and 3 versions of a single speaker model. Here's the data:
> 
> System	Framework	Quality	RTF (avg)
> Rpi4	PyTorch	Low	0.819
> Rpi4	Onnx	Low	0.494
> Rpi4	PyTorch	Med	1.255
> Rpi4	Onnx	Med	0.803
> Rpi4	PyTorch	High	8.081
> Rpi4	Onnx	High	5.307
> 5950x	PyTorch	Low	0.032
> 5950x	Onnx	Low	0.019
> 5950x	PyTorch	Med	0.046
> 5950x	Onnx	Med	0.030
> 5950x	PyTorch	High	0.167
> 5950x	Onnx	High	0.082
> I tested on a Raspberry Pi 4 with 4GB of RAM, and an AMD Ryzen 9 5950X with 64GB of RAM (latest torch 1.x and onnxruntime). On average, it seems the Onnx model has a 1.5-2x better RTF across the various model sizes. On the 5950x, you'd barely notice the difference but it's pretty pronounced on the Pi 4.
> 
> For fun, I tried Torchscript versions of the models too, but they were over 10x slower so I didn't include them in the table.

@synesthesiam does onnx framework mean running on cpu and pytorch framework mean running on gpu?

**Comment by synesthesiam** [comment]
It's all CPU in this case.
