### ISSUE TITLE
can this do speech to text too?

### ISSUE THREAD

**Issue by ralyodio** [rhasspy/piper#334]
I got the text to speech working, but I need the other direction now.

**Comment by synesthesiam** [comment]
No, Piper is text to speech only. You may want to check out [whisper](https://github.com/openai/whisper).

**Comment by ralyodio** [comment]
is there anythijng open source besides whisper which I assume requires payment for access to openai.com's api?

**Comment by rmcpantoja** [comment]
> is there anythijng open source besides whisper which I assume requires payment for access to openai.com's api?

Hi @ralyodio, 
Whisper is an open-sourced model. The model in the API is the same but only hosted for online usage.

**Comment by synesthesiam** [comment]
Vosk and Coqui STT are two other open source systems. Vosk is based on Kaldi, which can be used directly too.
