### ISSUE TITLE
How to use zh-cn-huayan-low.onnx

### ISSUE THREAD

**Issue by honyue** [rhasspy/piper#34]
I tried to generate a Windows project in the VS project, and the en-us-ryan-low.onnx worked properly, but the zh-cn-huayan-low.onnx generated incorrect speech,How can I make text encoding work properly?
![piper](https://user-images.githubusercontent.com/63630838/230774094-f25d0d8c-dcd8-4350-9372-27f2ef00be0d.png)
sound:
[sound.zip](https://github.com/rhasspy/piper/files/11185482/sound.zip)

**Comment by synesthesiam** [comment]
See the discussion here: https://github.com/rhasspy/piper/issues/9#issuecomment-1446060435

You need to copy cmn_listx and compile the extra dictionary.

**Comment by honyue** [comment]
> See the discussion here: [#9 (comment)](https://github.com/rhasspy/piper/issues/9#issuecomment-1446060435)
> 
> You need to copy cmn_listx and compile the extra dictionary.

Thank you very much for your reply. I will try again
