### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by daniel-lewis-ab** [rhasspy/piper#353]
So I excitedly went to github and cloned the repo.

I read the instructions here:

![image](https://github.com/rhasspy/piper/assets/12051895/79af6d70-7e27-498c-ac15-22260b0bcac9)

and basically couldn't make sense of it.

So I figured I could install it via Python, and ran pip install piper-tts.  That went fine.

So I used the example provided here:

![image](https://github.com/rhasspy/piper/assets/12051895/be11298c-6597-4c5c-8570-b7443e301866)

except after running this, the wav file doesn't have any sound.

So I tried running the other prompt, and also get no sound.

So umm, my point in all of this is that while it's probably running fine for some people, there are gaps in the explanation of how to get it up and running and what to expect of the process.  I suspect that rather than just helping me personally, it might be prudent to update the installation guides and/or make things easier/more thorough automatically.

Also, is there a discord channel?

**Comment by aaronnewsome** [comment]
I too had a rough go of it when I started to work with piper tts. I followed the instructions and failed. However, I was determined to get it working and I did. Since I've been there, I might be able to help but I'm not part of this project so updating the guides is not something I can do. If there is a Discord, I'm not aware of it.

Which Python version are you running, what Linux distro and which platform? From the above, I assume you're on Intel/AMD platform right?

**Comment by daniel-lewis-ab** [comment]
I'm running:
Python 3.10.12, 
Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy,
I'm on AMD Ryzen 5 3600,
NVIDIA GP106 [GeForce GTX 1060 6GB] vendor: eVga.com. driver: nvidia v: 525.147.05

I do write readme.md files, but I can only write the answers down on the paper if I can find the answers.  XD

**Comment by aaronnewsome** [comment]
Not sure what's going on in your system. I installed Linux Mint 21 in a fresh VM and once I enabled ssh, I connected to the system and ran exactly these commands:

```bash
sudo apt update && sudo apt upgrade -y
sudo apt install -y python3-pip
pip install piper-tts
export PATH="/home/anewsome/.local/bin:${PATH}"
echo $PATH
echo 'Welcome to the world of speech synthesis!' | piper   --model en_US-lessac-medium   --output_file welcome.wav
ls -sh welcome.wav 
```

The resulting welcome.wav was 100K and sounded just fine to me. Try running the piper command with "--debug" and post the result here.

**Comment by daniel-lewis-ab** [comment]
I got it working.  Thanks for your help.
