### ISSUE TITLE
Provide voice samples to showcase piper

### ISSUE THREAD

**Issue by HDembinski** [rhasspy/piper#40]
This is an awesome project.

Could you please provide some samples (ideally for each voice, but just one would already be great) in the readme, to showcase the quality of this tts?

Context: I only  recently learned about this library from a reddit post. Some people asked for an example to see how good the generated voices sound, and another redditor posted a one. I was really impressed by the quality.

**Comment by synesthesiam** [comment]
Finally got this put together :smile: 

https://rhasspy.github.io/piper-samples/
