### ISSUE TITLE
WARNING:preprocess:Missing piper_train.preprocess always skips the first file / utterance

### ISSUE THREAD

**Issue by bagobones** [rhasspy/piper#418]
I tried double checking if I had typos etc but for some reason piper_train.preprocess always tosses an error and skips the first file in the the metadata.csv.

I resorted to duplicating the first file with a new name, then putting a duplicate entry in the metadata.csv (same text) just different name.

The new duplicate / first file still gets skipped but at least it counts all the utterances now

**Comment by brunopiovan** [comment]
it happened to me when I had the UTF8 BOM (byte order mark) in the file... open your file in a hex editor and check the first 3 bytes / make sure you save it without bom

**Comment by bagobones** [comment]
> it happened to me when I had the UTF8 BOM (byte order mark) in the file... open your file in a hex editor and check the first 3 bytes / make sure you save it without bom

I shouldn't have closed without commenting but the issue appears to have been due to running under WSL2 on windows, it can leave file handles open / not remove files.. After closing all WSL2 terminals and starting again the problem went away.
