### ISSUE TITLE
2 notes!

### ISSUE THREAD

**Issue by ican24** [rhasspy/piper#42]
1. The piper_train.export_onnx sript does not worked properly. You need to change parameters manually adding "--" before the parameters.
```
    parser.add_argument("--checkpoint", help="Path to model checkpoint (.ckpt)")
    parser.add_argument("--output", help="Path to output model (.onnx)")

```
2. if you run piper with other model, add --config to your config.json file․
`echo 'Մենք ողջունում ենք Ձեզ' | ./piper --model hymodel.onnx --config config.json --output_file test.wav`

**Comment by synesthesiam** [comment]
Hi @ican24,

1. Not having `--` before the parameters means they're positional and required
2. Yes, `piper` looks for a config automatically with the name of `<model>.onnx.json` so you have to override this if it's different
