### ISSUE TITLE
Assist is translating my request, and then failing to comply

### ISSUE THREAD

**Issue by davidrpfarinha** [rhasspy/piper#428]
Hey there,

When using Piper as source for translation of my Assist within Home Assistant, I'm using Portuguese as the language.
Although, for it translates my sentence to English which then seem to make the Assist to be able to recognize the command.
![image](https://github.com/rhasspy/piper/assets/7164089/46db4d78-0311-46d6-a97d-3e7ec65ce734)

Did I misconfigure something? I don't think so, as it was working in the past, and if I run the text pipeline, it does work as expected.
![image](https://github.com/rhasspy/piper/assets/7164089/7ed05398-a929-4d2b-8980-a71207e881dd)

Cheers

**Comment by synesthesiam** [comment]
Assist doesn't translate anything, so it looks to me like everything is working correctly. A Portuguese pipeline should fail with an English sentence, no?

**Comment by davidrpfarinha** [comment]
What you are saying does make sense, but I have everything set to Portuguese 😅 Could I be missing something else?
![image](https://github.com/rhasspy/piper/assets/7164089/7c900afe-0792-4b2d-a151-aec20dc6fca3)

**Comment by llluis** [comment]
`Just to confirm, the voice command was spoken to Piper in Portuguese, which then translated to English, and that is what you are seeing on the first screenshot. `

That’s whisper not piper. Piper is the output which is in Portuguese. 

Are you on HA 2024.3.0 ?

**Comment by davidrpfarinha** [comment]
> > Just to confirm, the voice command was spoken to Piper in Portuguese, which then translated to English, and that is what you are seeing on the first screenshot.
> 
> That’s whisper not piper. Piper is the output which is in Portuguese.
> 
> Are you on HA 2024.3.0 ?

Ohhh that’s right 🤦‍♂️
Yes, I’m. But this was already happening in the previous version.

**Comment by llluis** [comment]
This screenshot says PT:

![image](https://github.com/rhasspy/piper/assets/708868/2a9cfed7-d4a7-4955-baea-ccfbd2b5de7a)

But this EN:

![image](https://github.com/rhasspy/piper/assets/708868/16aca675-6639-4a70-a6b3-2e03d31c8ff4)

Something seem wrong.

**Comment by davidrpfarinha** [comment]
> This screenshot says PT:
> 
> ![image](https://private-user-images.githubusercontent.com/708868/310905008-2a9cfed7-d4a7-4955-baea-ccfbd2b5de7a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjEzMDAsIm5iZiI6MTcwOTgyMTAwMCwicGF0aCI6Ii83MDg4NjgvMzEwOTA1MDA4LTJhOWNmZWQ3LWQ0YTctNDk1NS1iYWVhLWNjZmJkMmI1ZGU3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNDE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmZiYjViMmUwOGNiZDk3M2U5YmYyMmE5YzcyOGQwZmU5ZWU1MTJmNGY1YTJjNjdjZTliYTVlZGViZDZlNjA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7rduFv7hvoktRFkxW8FGaO3R0aY12KnTcYZWyB-uM8w)
> 
> But this EN:
> 
> ![image](https://private-user-images.githubusercontent.com/708868/310905099-16aca675-6639-4a70-a6b3-2e03d31c8ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjEzMDAsIm5iZiI6MTcwOTgyMTAwMCwicGF0aCI6Ii83MDg4NjgvMzEwOTA1MDk5LTE2YWNhNjc1LTY2MzktNGE3MC1hNmIzLTJlMDNkMzFjOGZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxNDE2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjA1ZTc4M2IzNDUwNGU2ZTRlYjZjMTJlMGQ1NDQyMjY0MzQzZDlmM2VhNTAxMzExMTRmMGI1YzE5NjMzMjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8PNsrjnG8tznMMNpknogVlhu8zAESWchs2-dfOJo7f4)
> 
> Something seem wrong.

Yes, that was what I wanted to understand. Because, I did created the container as English at first, but then noticed that you can select other languages within the configurations. I thought that it could be default vs actuals. Nevertheless, I might need to create a new portuguese container, and see if that solves the issue.

**Comment by llluis** [comment]
In theory you are correct, the Assist pipeline config shall be able to use the settings different from the container. But I'm still intrigued how the Portuguese speech got translated to English. :D

I'm also using voice in Portuguese and this never happened.

**Comment by davidrpfarinha** [comment]
> In theory you are correct, the Assist pipeline config shall be able to use the settings different from the container. But I'm still intrigued how the Portuguese speech got translated to English. :D
> 
> I'm also using voice in Portuguese and this never happened.

If you don't mind, can you share your Container configs?
The odd thing is, I didn't change anything, as far as I can recall of course, and it was working in the past.

**Comment by davidrpfarinha** [comment]
Did create a new whisper container with PT as default, and that sorted out.
Although, I don't understand how in the past this worked, but now is failing. 🤷‍♂️ 

  whisper-portuguese:
    container_name: whisper-portuguese
    image: rhasspy/wyoming-whisper:latest
    command: --model base-int8 --language pt
    volumes:
      - /volume1/docker/whisper-portuguese:/data
    environment:
      - TZ=Europe/Lisbon
    restart: unless-stopped
    network_mode: "host"
    ports:
      - 10300:10300

**Comment by davidrpfarinha** [comment]
Closing this, and moving it to rhasspy/wyoming-faster-whisper.
