### ISSUE TITLE
Nice work, where to download the Chinese pretrain model though?

### ISSUE THREAD

**Issue by lucasjinreal** [rhasspy/piper#43]
Nice work, where to download the Chinese pretrain model though?

**Comment by synesthesiam** [comment]
Thanks! The Chinese model is here: https://github.com/rhasspy/piper/releases/download/v0.0.2/voice-zh-cn-huayan-x-low.tar.gz

**Comment by svenha** [comment]
In the meantime, there is also a medium-sized model at the end of: https://github.com/rhasspy/piper/releases/tag/v0.0.2

**Comment by synesthesiam** [comment]
Checkpoints are here: https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main
