### ISSUE TITLE
Add Direct Links  To More Voices

### ISSUE THREAD

**Issue by tvraman** [rhasspy/piper#435]
Could you please add more direct download links for voices in the readme.md file; at present you have one as an example. But the various pages where other models live are a maze of links and  is hard to use -- especially if one cannot see

**Comment by luiscarlos2000** [comment]
I was asking the same question since it-s beginning. I also need additional repositories a longside the official one.

**Comment by tvraman** [comment]
the problem is somewhat eased by the data in voices.json and the  piper
executable's option of --update-voices; could be better documented to
say that that works only if the datasets dir is writeable by the user
running piper.

Also the Hugging Face site though well-structured to reflect the
underlying datastore is a mess to navigate -- wish someone had a
programmatic API client for it.


--

**Comment by synesthesiam** [comment]
I could generate a markdown file with links to all the voices. Something like:

```markdown
* English (U.S.)
    * Lessac
        * Low (link)
        * Medium (link)
        * High (link)
```

Would this be any better?

**Comment by tvraman** [comment]
that would be awesome!

--

**Comment by synesthesiam** [comment]
It's live now! https://github.com/rhasspy/piper/blob/master/VOICES.md

**Comment by tvraman** [comment]
Nice, Thanks for all your work on Piper  -- it's a very nice piece of
work.

--
