### ISSUE TITLE
how to trun pth  to  onnx?

### ISSUE THREAD

**Issue by cgisky1980** [rhasspy/piper#46]
```
/piper/src/python/piper_train$ python export_onnx.py checkpoint G_latest.pth output G_latest.onnx
Traceback (most recent call last):
  File "/www/piper/src/python/piper_train/export_onnx.py", line 9, in <module>
    from .vits.lightning import VitsModel
ImportError: attempted relative import with no known parent package

```

**Comment by cgisky1980** [comment]
i train my voice by https://github.com/Plachtaa/VITS-fast-fine-tuning

**Comment by athenasaurav** [comment]
You're running the program from the wrong directory. if you are running from piper train then manually remove "." from the original codes. So from ```.vits.lightning import VitsModel``` will become ```from vits.lightning import VitsModel```
