### ISSUE TITLE
Voice files in Safetensors format?

### ISSUE THREAD

**Issue by MackNcD** [rhasspy/piper#474]
I'd love to use Piper for my program but there are no safetensor models for the voice models, so I can't guarantee people will be safe to use it. Can you guys convert the models to safetensors? Or will the program at least read them if I convert myself?

**Comment by nmstoker** [comment]
Which part(s) of piper do you think is/are unsafe?

Looking at the README for safetensor they highlight that they provide safety **by avoiding pickle,** yet pickle isn't used in this repo, it uses onnx. The onnx/protobuf entry in the table in the safetensor repo marks it as safe so I'm not convinced of the validity of your concern, but do say if there's a particular aspect I'm overlooking.

**Comment by synesthesiam** [comment]
Yeah, this doesn't make sense to me either. Piper voices are onnx, which does not use pickle.
