### ISSUE TITLE
Can I continue training from an ONNX model?

### ISSUE THREAD

**Issue by airtnqls** [rhasspy/piper#48]
Hi there,
I have an ONNX model that I would like to continue training on, but I'm not sure if this is possible or if I need to convert it to CKPT format first. I understand that I can continue training from a CKPT checkpoint file, but I'm not sure if the same can be done with ONNX. Can someone please advise if it's possible to continue training from an existing ONNX model or if I should convert it to CKPT format before proceeding? Thank you in advance for your help.

**Comment by synesthesiam** [comment]
No, you can only resume from a full checkpoint. This is because a big chunk of the training information is discarded when exporting to ONNX (specifically, the discriminator).

For the same reason, you also can't convert ONNX back into a checkpoint.
