### ISSUE TITLE
I want to train with python3.12.3, but I caught this

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [rhasspy/piper#489]
ERROR: Could not find a version that satisfies the requirement piper-phonemize~=1.1.0 (from piper-train) (from versions: none)
ERROR: No matching distribution found for piper-phonemize~=1.1.0

**Comment by porky11** [comment]
Same issue. Did you find a solution, since you already closed it?

**Comment by shangzh0** [comment]
python3.8 i met this error too
