### ISSUE TITLE
How can I use Piper TTS voices with Google Talkback?

### ISSUE THREAD

**Issue by mikebayus** [rhasspy/piper#510]
Hi.

I am totally blind, and I am enjoying the Sonata TTS voices for the NVDA Screen Reader.

I would really like to have Piper TTS voices on my Google Android Phone so I might enjoy them with my Google Talkback Screen Reader as well.

Is that possible?

**Comment by luiscarlos2000** [comment]
Ya know, I was also asking the same question as you, but more generally. E.G. Using Piper TTS as my engine for GPS apps and other such things. I'm using Jieshwo screen reader, which oh, surprise surprise, I'm the spanish translator.

**Comment by mikebayus** [comment]
My favorite voice is the Librits_R voice and Speaker #1851.

I would like to have this voice as the default voice for my Google Pixel 7
pro Phone as well as my Windows PC.

I amtotally blind and I am running windows 11 and I have NVDA as my Screen
Reader, and I would like to have the same voice across both platforms.

It would really be nice if these great Piper Neural TTS voices could be
SAPI5 compliant as well.

**Comment by luiscarlos2000** [comment]
Totally blind since birth? What a connection we have! Me, also totally blind, but here's the difference: My old dell laptop running Windows 11 insider, my new HP laptop running Windows 10, my 12 year-old desktop Dell pc running Windows 11... I believe that's... umm... truely something...
You've catched me about Piper tts supporting Sapi5 protocol! That way I want to play my games or do other stuff, even using Narrator with piper neural voices. Have 160 or so voices installed, including mine.

**Comment by willwade** [comment]
I'm working on this - in our VoiceBroker project - at least making it a SAPI engine in Windows. Its tough but watch this space

**Comment by mikebayus** [comment]
Oh boy!

I would really like to be able to have Piper TTS voices for such apps
like:  Kindle for PC, Balabolka, Narrator, and other SAPI5 software that
uses TTS.

As one who is totally blind from birth, I can say it's a real shame that we
blind people have to be content with TTS voices that were developed back in
2006 and earlier.

It's really not fair that Microsoft should make it so tough.

I'll be looking forward to a link once you get it working.

**Comment by mikebayus** [comment]
Hi.

I downloaded the Piper speech engine that I wanted to my Android phone, but
I can't figure out how to chuse the speaker I want.

Right now, I have speaker #0987, and I want #1851.

How do I change that setting?

Otherwise the engine works great?

Thank you so much.

**Comment by csukuangfj** [comment]
Could you us which model/apk you have downloaded?

You can change speakers only for models that have multiple speakers.

**Comment by mikebayus** [comment]
I downloaded the Librits_R US english voice.

I am totally blind, and I am running the NVDA Screen reader on my Windows
PC.

I have the Sonata TTS addon, and I am running the Librits_R Piper voice
model, and I really like Speaker ID #1851, and that's the voice I want on
my Phone.

I no about multiple speakers, I just don't know how to pick #1851 for my
phone.

It's pretty straight forward for NVDA, al you do is pick it.

How do I pick it for my Phone?

**Comment by csukuangfj** [comment]
According to https://huggingface.co/rhasspy/piper-voices/blob/main/en/en_US/libritts_r/medium/en_US-libritts_r-medium.onnx.json#L849

speaker ID `#1851` is 351.

Please set speaker ID to 351

**Comment by csukuangfj** [comment]
For the following sample sentence
```
This is a sample sentence, generated using the speaker ID three hundred and fifty one, which is mapped to the original speaker ID eighteen fifty one.
```

The generated wav is posted below

(It was generated using https://huggingface.co/spaces/k2-fsa/text-to-speech)

https://github.com/rhasspy/piper/assets/5284924/edba5885-d499-45e2-9dbb-f40d79023bc2

**Comment by mikebayus** [comment]
That's it!

Thank you so much.

Now, is there a way to save that setting for the future?

Now that I know how to do it, I can set the speaker ID without sighted
assistance, but I find that if I restart my Phone, and my Talkback screen
reader comes up, that it defaults to the 903 setting and I would have to
reset my 351 speaker ID again.

Is there any way to save that setting so I won't have to reset it again?

Not that I restart my phone that often.

It's just that I would be appriciative if there was a way to save new
speaker ID settings.

Again, thank you so much.

All best,
Mike

**Comment by csukuangfj** [comment]
> Is there any way to save that setting so I won't have to reset it again?


Yes. Please wait for our next release.

**Comment by mikebayus** [comment]
Will I be able to get to it using the link that you pointed me too?

**Comment by csukuangfj** [comment]
> https://k2-fsa.github.io/sherpa/onnx/tts/apk-engine.html

Yes. I will let you know when it is ready.

**Comment by mikebayus** [comment]
That would be much appreciated.

Thank you.

**Comment by csukuangfj** [comment]
Released. Please try version 1.9.28

@mikebayus

**Comment by mikebayus** [comment]
How do I update?

do I just click on the link as before?  And must I uninstall the old one?

**Comment by csukuangfj** [comment]
1. Download the app
2.  Install it. (It will automatically replace the previous installed one)

**Comment by csukuangfj** [comment]
Does it work?

**Comment by mikebayus** [comment]
Yes!

It does work.

I got scared though, because the #903 speaker ID was still showen in
Parentheses.

But when I restarted my phone, Speaker ID #351 was still the voice that
came up when Talkback was launched.

I got your EMail just as I was about to get into bed last night, or rather
this morning, as it was just after midnight.

i am in Florida USA, and therefore I am on EDT.

As I am blind, and as I use talkback to hear what is on screen, I must
locate the right file by hearing one file name read at a time.

So it takes me some time to find the speech engine that I want.

So when I got up this morning, and after a good Breakfast, I got to work
and the whole thing  took me about an hour.

That's why I didn't answer you right away last night.

Thank you so much.

I think we can close my Piper issue now.

Best,
Mike

**Comment by csukuangfj** [comment]
> So it takes me some time to find the speech engine that I want.

Sorry. I should have sent you the link to the model directly for downloading.

Great to hear that it solves your issue.

**Comment by mikebayus** [comment]
Next time we'll know.

Let's keep in touch..

**Comment by mikebayus** [comment]
Issue fixxed.
