### ISSUE TITLE
Is there a list of reserved keywords? It can't say "prompt", "debugging", or "watching"

### ISSUE THREAD

**Issue by 5-tom** [rhasspy/piper#515]
Is there a list of forbidden words that can't be passed to the program? I'm resorting to using hacks like:

"prompt" --> "prohmpt"
"debugging" --> "de-bug-ing"
"watching" --> "watch-ing"

Using the words as-is causes the program to crash, predictability.

**Comment by colbec** [comment]
Hmm, 

`echo 'well well prompt and watching might be debugging a hard word' | piper --model data/jpiper/models/en_US-ryan-medium.onnx --output_file welcome.wav`

seems to work for me. Maybe some other factor involved that you have not shared yet: voice, quality? Made any chngest to fundamental program components? I'm using Linux.

**Comment by synesthesiam** [comment]
There isn't any list of words that can't be used. How are you using Piper?

**Comment by 5-tom** [comment]
Hey,

The bug I was encountering has been better explained [here](https://github.com/rhasspy/piper/issues/520), so I'm going to close this issue.
