### ISSUE TITLE
How can I get phoneme time alignments?

### ISSUE THREAD

**Issue by AndySze** [rhasspy/piper#531]
Thank you for your great project. Is there a way to obtain phoneme time alignments?    
I know that piper_phonemize can output the phonemes, but how can I include the time alignments, like this:  
```
# start_time duration phoneme
0.210 0.045 æ
0.390 0.045 l
0.450 0.045 u
0.540 0.045 s
0.630 0.045 ɔ
0.720 0.045 ɹ
0.870 0.045 s
```

**Comment by synesthesiam** [comment]
This is coming in the next version of Piper :+1:
