### ISSUE TITLE
get error for add new speaker to a multi-speaker checkpoint 

### ISSUE THREAD

**Issue by mniiinm** [rhasspy/piper#568]
If the checkpoint is multi-speaker, For example, Checkpoint has 2 speakers and I want to finetune it and add a new speaker to it, so that it becomes 3. It's impossible?
i get this error:
size mismatch for model_g.emb_g.weight: copying a param with shape torch.Size([2, 512]) from checkpoint, the shape in current model is torch.Size([3, 512]).

**Comment by synesthesiam** [comment]
That is correct. A new speaker can't be added by extending the number of speakers since that changes the size of the network.

You can fine tune to replace an existing speaker, or have some speaker ids left unused for the future.
