### ISSUE TITLE
turkish language

### ISSUE THREAD

**Issue by tuncay59** [rhasspy/piper#58]
Will there be Turkish language support?

**Comment by synesthesiam** [comment]
@tuncay59 I have one volunteer so far to read Turkish sentences for a dataset. If you'd like to volunteer, please send me an e-mail at voice@nabucasa.com

**Comment by synesthesiam** [comment]
I'm planning to train a voice from this dataset: https://github.com/marytts/dfki-ot-data/

**Comment by synesthesiam** [comment]
The `tr_TR-dfki-medium` is now available with Piper 1.2.0
