### ISSUE TITLE
Not able to change language 

### ISSUE THREAD

**Issue by Rrapa** [rhasspy/piper#61]
Hi guys

I'm trying to use pl-mls_6892-low but looks like constantly have uk-lada-x-low and not able to change even if I use english - ukr stays . .can you advice ? 

Thank you

Rafal

**Comment by synesthesiam** [comment]
When running Piper, make sure to change `--model` to the voice you want

**Comment by Rrapa** [comment]
> When running Piper, make sure to change `--model` to the voice you want

Not sure what u mean ? Where ? In piper confi?

**Comment by synesthesiam** [comment]
On the command line. How are you running Piper?

**Comment by Rrapa** [comment]
I have piper installed via add-ons and was testinh it via Media

**Comment by Rrapa** [comment]
So I'm changing that obviously and voice wasn't changing. I was reloading addin reloading HA and reloading whole system

**Comment by HobisPL** [comment]
Try to provide the full path to the model.
