### ISSUE TITLE
Consistent nameing of voice archives

### ISSUE THREAD

**Issue by mush42** [rhasspy/piper#62]
Hello,

When integrating Piper with clients (such as [NVDA](https://github.com/nvaccess/nvda)) we need a consistent way to discover and list available voices.

Many, but not all, of Piper voices follow the following naming scheme:

```bash
voice-{language}-{name}-{quality}
```

I suggest renaming existing voices to strictly conform to this naming scheme, and making sure that new voices are consistent with it.

Also, any intermittent seperators should be underscores `_` rather than dashes `-`.

For instance, `en_US` instead of `en-US` and `southern_english_female` instead of `southern-english-female`.

 Best
 Musharraf

**Comment by synesthesiam** [comment]
I'm considering using double dashes `--` as a separator so that dashes can be used in voice names. What do you think?

**Comment by mush42** [comment]
@synesthesiam 

That will do the trick.

But wouldn't that conflict with command line args that expect `voice name` as a value?

**Comment by synesthesiam** [comment]
Hmmm...good point. Maybe double underscores 😄

**Comment by mush42** [comment]
Simply put: dashes to separate the various segments, underscores for everything else 😄

**Comment by synesthesiam** [comment]
New voices will be following your underscore convention :+1:

**Comment by mush42** [comment]
Thanks @synesthesiam
