### ISSUE TITLE
Piper Neural voices can not load when using the Sonata Voice Manager in Sonata Neural Voices for NVDA

### ISSUE THREAD

**Issue by mikebayus** [rhasspy/piper#622]
Hello all,

I have also reported this to the Sonata issues page, but I don't know if this is a problem with the Sonata Voice Manager or if Piper voices download has been updated so they will no longer work for the NVDA add-on.

I am running the latest NVDA version, and the latest version of the Sonata add-on.

The voice I had worked fine until I removed it because I wanted to try another voice.

Now, when I chuse a voice from the Sonata Voice Manager, and press the download butten, I get the error message:

Download failed.  the voice can not be downloaded.  Make sure you are connected to the internet and try again.

Then I get an O.K. button.

No matter which voice I try, I get the same error.

I know I have a good internet connection, because all of my other pages and web sites load just fine.

I am not a computer programer, so I only know to click the download button.

I have lost my favorite voice in NVDA, and I want it back.

I have told the Sonata community of this issue, but as I have not heard from them, I am telling you as well.

Any chance that someone might be working on Piper Voices for SAPI5"

I know that Microsoft makes that a really hard task.

Thank to all for considering this issue.

**Comment by mikebayus** [comment]
Is it time to renew your SSL Certificate?

This is from my NVDA log file when I try to download a piper voice from the sonata voice manager.

ERROR - external:globalPlugins.sonata_tts_global_plugin.voice_download.PiperVoiceDownloader.done_callback (14:21:23.645) - ThreadPoolExecutor-0_0 (10656):
Failed to download voice.
Exception: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)
Traceback (most recent call last):
  File "C:\Users\micha\AppData\Roaming\nvda\addons\sonata_neural_voices\synthDrivers\sonata_neural_voices\lib\mureq.py", line 167, in yield_response
    conn.request(method, path, headers=headers, body=body)
  File "http\client.pyc", line 1303, in request
  File "http\client.pyc", line 1349, in _send_request
  File "http\client.pyc", line 1298, in endheaders
  File "http\client.pyc", line 1058, in _send_output
  File "http\client.pyc", line 996, in send
  File "http\client.pyc", line 1475, in connect
  File "ssl.pyc", line 517, in wrap_socket
  File "ssl.pyc", line 1104, in _create
  File "ssl.pyc", line 1382, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

I reported this on the Sonata neural voices for NVDA issues page, but I don't know if this would be an issue for them, or for you.

I want my piper voices back, and I don't know who to tell.

I made a mistake in removig my piper voice, not knowing that I would not be able to download it again.

I know I screwed up.

Can someone please help?

**Comment by trandangminhson09002200003-droid** [comment]
xin chào tôi là người việt nam và tôi cũng mới biết add-on neural voices cho NVDA cũng đang bị lỗi như những gì người ấy viết.
và hi vọng tác giải viết add-on này sẽ khắc phục lỗi này..
Và luôn tiên tôi hỏi là add-on này có giọng nói tiếng việt không và nếu có thì mong mussh42&piper cho chúng tôi biết nhé thank you.
