### ISSUE TITLE
Turkish Model verry buggy on windows release

### ISSUE THREAD

**Issue by DarkCamper242** [rhasspy/piper#630]
the windows version of the piper tts can not voice any special characters in Turkish, for example, "ı ü ğ ö ç j"

Any solutions ?

**Comment by DarkCamper242** [comment]
> hayir , duzgun calisiyor. Siz fine tuning model yaptiniz mi ? ilk mi

Hayır finetune yapmadım piper in kendi türkçe modellerini windows sürümü üzerinde denedim türkçe deki özel karakterlerin hiçbirini söylemiyor onun yerine önceki harfi uzatıyor

**Comment by eix128** [comment]
bende java surumunu yazdim daha yayinlamadim.
Windows da duzgun de calisiyor

**Comment by DarkCamper242** [comment]
> bende java surumunu yazdim daha yayinlamadim. Windows da duzgun de calisiyor. Yayinlayacagim sene basi gelmeden. Haber ederim java kullaniyorsan

Ben python a bir api yaptım pyttsx3 gibi fakat piper.exe ile komut penceresinden dahi yapsam tuhaf tuhaf çıktılar veriyor sizde model dosyası varsa verebilirmisiniz

**Comment by eix128** [comment]
haa sen cmd den yapmaya calisiyorsun.
"chcp 65001"
yaz komut olarak sonra dene exe yi

**Comment by DarkCamper242** [comment]
oldu harbi teşekkür ederim konu kilit
