### ISSUE TITLE
Ubuntu 22.04LTS 
Cannot run pip install piper-tts

### ISSUE THREAD

**Issue by mylegitches** [rhasspy/piper#642]
Install fails:
$ pip install piper-tts
Collecting piper-tts
  Using cached piper_tts-1.2.0-py3-none-any.whl.metadata (776 bytes)
INFO: pip is looking at multiple versions of piper-tts to determine which version is compatible with other requirements. This could take a while.
  Using cached piper_tts-1.1.0-py3-none-any.whl.metadata (776 bytes)
ERROR: Cannot install piper-tts==1.1.0 and piper-tts==1.2.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    piper-tts 1.2.0 depends on piper-phonemize~=1.1.0
    piper-tts 1.1.0 depends on piper-phonemize~=1.0.0
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by mylegitches** [comment]
It was resolved by:

sudo apt update
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.10
sudo apt install python3.10-venv
python3.10 -m venv piper
source /piper/bin/activate
python -m pip install pip==24.0
pip install piper-tts


I hope this helps anyone else with the issue!

**Comment by qt06** [comment]
You can change the requirements.txt.
Change the piper-phonemize to piper-phonemize-cross.
Change the pytorch-lightning version to 1.9.0
