### ISSUE TITLE
ARMv7 (32-bit only ARM) support

### ISSUE THREAD

**Issue by renekliment** [rhasspy/piper#67]
Hi! Thank you for this awesome and high quality project that I believe will be one of the parts that will make _the_ difference in the world of open-source voice assistants.

Would it be possible to also support ARMv7 and publish builds/releases for this platform? 
I have an Orange Pi+ 2E, which is a sort of old, but still a very powerful SBC to run Home Assistant and it would be awesome if it could run piper to have high-quality fully local TTS.

**Comment by synesthesiam** [comment]
You're welcome! A major barrier to ARMv7 support is that Microsoft does not provide 32-bit builds of their ONNX runtime. I've managed to build them in the past, but haven't had success recently.

If anyone is willing to provide up to date 32-bit ONNX runtime builds for me, I can include an ARMv7 version.

**Comment by mkiol** [comment]
I'm using Piper lib with my app on ARMv7 without any problems. I've managed to build ONNX runtime with Linaro GCC 8.2. Here is the [binary](https://github.com/mkiol/dsnote/releases/download/v3.0.0/onnxruntime-linux-arm32-1.14.tgz).

@synesthesiam Thank you for this amazing project ❤️.

**Comment by Wetzel402** [comment]
Plus one for this feature request.

**Comment by Kaeybe** [comment]
Hi! Thank you for your awesome project, i have a Raspberry Pi 3 and work very well... Can mkiol idea resolve the problem ?

**Comment by synesthesiam** [comment]
Oddly, I'm stuck trying to compile [my espeak-ng fork](https://github.com/rhasspy/espeak-ng) for 32-bit ARM now. It builds the `espeak-ng` binary, but won't compile the voices for some reason. Same build process works fine on 64-bit ARM :man_shrugging:

**Comment by mkiol** [comment]
> It builds the `espeak-ng` binary, but won't compile the voices for some reason.

Maybe the problem is the same as in my case. I came across something like this:

```
cd dictsource && ESPEAK_DATA_PATH=/work ../src/espeak-ng --compile="af"
Error: The specified espeak-ng voice does not exist.
make[1]: *** [Makefile:3213: espeak-ng-data/af_dict] Error 1
```

The problem was [here](https://github.com/rhasspy/espeak-ng/blob/61504f6b76bf9ebbb39b07d21cff2a02b87c99ff/src/libespeak-ng/voices.c#L1216). `readdir` returned NULL because (as I learned) on 32-bit systems you need to add compilation flag `-D_FILE_OFFSET_BITS=64` to me it work properly.

This 👇🏿  resolved the issue in my case:

```
export CFLAGS=-D_FILE_OFFSET_BITS=64 && ./autogen.sh && ./configure
```

Hope this helps.

**Comment by synesthesiam** [comment]
@mkiol That was it, thank you so much! A 32-bit version of Piper is now available: https://github.com/rhasspy/piper/releases/download/v1.0.0/piper_armv7.tar.gz

**Comment by renekliment** [comment]
I only got to run it today and it is great! Running happily on my Orange Pi. :orange_heart:  Thank you!
