### ISSUE TITLE
Missing python header

### ISSUE THREAD

**Issue by MelissaFrog** [rhasspy/piper#71]
When running the build_monotonic_align.sh script, I get the following error.

piper-master/src/python/piper_train/vits/monotonic_align/core.c:18:10: fatal error: Python.h: No such file or directory
   18 | #include "Python.h"
      |          ^~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

Any suggestions?

Regards,
Joe

**Comment by synesthesiam** [comment]
Yes, make sure to `sudo apt-get install python3-dev`
I'll add a note to the README about it.

**Comment by MelissaFrog** [comment]
That took care of my problem.  Thank you.

Joe

**Comment by JoeHogan** [comment]
similar error even after running sudo apt-get install python3-dev. Also rebooted?

 command 'x86_64-linux-gnu-gcc' failed: No such file or directory
