### ISSUE TITLE
espeak-ng-data\phontab': No such file or directory

### ISSUE THREAD

**Issue by lucasjinreal** [rhasspy/piper#73]
where to download this?

espeak-ng-data\phontab': No such file or directory

**Comment by mush42** [comment]
Hi @lucasjinreal 

What operating system you're running?

The error means that eSpeak couldn't find the `espeak-ng-data` directory in the location it expects.

Best

**Comment by mush42** [comment]
Hi @lucasjinreal 

What operating system you're running?

The error means that eSpeak couldn't find the `espeak-ng-data` directory in the location it expects.

Best

**Comment by lucasjinreal** [comment]
@mush42 am using windows, I actually downloaded espeak-ng-data from repo and unzip, but there is only `lang` and `voices` there, no such `phontab`, where to get it?

**Comment by lucasjinreal** [comment]
@mush42 hello, may I ask for a help? You guys familliar with espeak-ng must know this, please tell me how can I resolve it.

**Comment by mush42** [comment]
The easiest way is to download a prebuilt version of espeak-ng.

**Comment by lucasjinreal** [comment]
@mush42  Can u please kindly guides me more?

![image](https://github.com/rhasspy/piper/assets/21303438/f34a86b8-8169-43a3-876f-bba249ca2e9e)

I didn't saw there is a packaged file which might contains data......

**Comment by mush42** [comment]
Actually, either one of the installers will do.

Installing eSpeak-ng will add a key to the registry, containing the path to `eSpeak-ng-data` directory, which eSpeak-ng.dll will then pick up.

Best

**Comment by synesthesiam** [comment]
A Windows pre-release is now available here: https://github.com/rhasspy/piper/releases/tag/2023.9.9-1

**Comment by Alavi100** [comment]
> @mush42 Can u please kindly guides me more?میشه لطفا بیشتر راهنماییم کنید
> 
> ![image](https://private-user-images.githubusercontent.com/21303438/238248340-f34a86b8-8169-43a3-876f-bba249ca2e9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwNjc1MDcsIm5iZiI6MTczNjA2NzIwNywicGF0aCI6Ii8yMTMwMzQzOC8yMzgyNDgzNDAtZjM0YTg2YjgtODE2OS00M2EzLTg3NmYtYmJhMjQ5Y2EyZTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA1VDA4NTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZGRkZmI4Mjc1ZjRlOTM5NTQ5YTU2MzQ4ZDkwMThlMDU2Y2I5Mzk1YWVlYjI2ZGVmYTY3OTZhODIyODYwMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GzMDo6tSJtygu3j1-HiF1E6LguInUjPz7Pw9WcQFxQE)
> 
> I didn't saw there is a packaged file which might contains data......من ندیدم فایل بسته بندی شده ای وجود دارد که ممکن است حاوی داده باشد......

https://github.com/espeak-ng/espeak-ng/releases/download/1.52.0/espeak-ng.msi
