### ISSUE TITLE
Slovak language support

### ISSUE THREAD

**Issue by Pheggas** [rhasspy/piper#75]
Hello. Mozilla has pretty interesting project called Common Voice where people record their voice. We already have 29 hours of voice recorded and it's free to download.

Could you please add Slovak language using Common voice to Piper?

**Comment by LukasFrinn** [comment]
Hi @Pheggas 
I just started recording Slovak language via Piper Recording Studio yesterday :D

**Comment by synesthesiam** [comment]
@Pheggas Common Voice is meant for speech to text models, so it has many speakers in noisy environments. Text to speech needs many samples from a single speaker in a quiet environment.

@LukasFrinn Let me know when it's ready and I'll train a voice :)
