### ISSUE TITLE
Czech language support

### ISSUE THREAD

**Issue by RimanCz** [rhasspy/piper#77]
I understand that adding languages is not an easy task, and I know that it cannot be rushed. However, I would like to ask if there are any plans to add Czech language support in the future, and if so, is there an estimated timeframe for its addition? I would greatly appreciate it.
Thank you.

**Comment by synesthesiam** [comment]
I don't currently have any Czech data. If you're interested in volunteering, please e-mail me at voice@nabucasa.com :slightly_smiling_face:

**Comment by RimanCz** [comment]
Okey, thanks for info!

**Comment by urtzai** [comment]
Thanks for the response! OK, I'm just contacting people to do this task. By the way, I created a [pull request](https://github.com/home-assistant/intents/pull/1408) with some intents for Home Assistant and the Year of Voice project. Do you know if this requests are going to be merged (or more or less when) so I can move on with the complete integration of the language in HA?

Thanks and sorry, for responding in this thread. When I have some news, I will create a new issue.
