### ISSUE TITLE
Preprocessing step (feature request)

### ISSUE THREAD

**Issue by Shulyaka** [rhasspy/piper#78]
Okay, I am not a linguist, but as far as I understand there is a problem that many languages (including English) have no inherent rules for which syllable should be stressed. Hence, the neural network can't learn that without being fed with an entire dictionary recorded by someone.
May I suggest an improvement? I think we need two neural networks working in a sequence. The first will annotate the text with emphasis/stress marks, and the second one will generate the sound.
The benefit is that we don't need a human to read it all out to train the first (preprocessing) network. We can create a huge training dataset with just a dictionary.
And we also don't need to rerecord the all the existing samples - just annotate the existing dataset an retrain.
The idea is that some aspect of the spoken language don't really require human speech to train, just a dictionary. All those things to dot the i's and cross the t's to exclude all ambiguity like replacing "Е" with "Ё" where needed in Russian (some texts in Russian often use "Е" in place of a "Ё").
Also would be good at this stage to convert numeric (arabic or roman) numbers into text, unpack abbreviations, etc.
I believe this would give us a much better performance and greatly reduce the required number of audio samples for the same output quality.
In the future we may add some more annotations like suggested intonation or character, like excitement or confusion.

**Comment by Shulyaka** [comment]
While learning about espeak I have realized I might be reinventing the wheel...

**Comment by synesthesiam** [comment]
espeak-ng should already produce stress through the standard IPA primary/secondary stress characters. If it isn't, this is something we need to report upstream and get fixed :slightly_smiling_face:

**Comment by Shulyaka** [comment]
Thank you!
