### ISSUE TITLE
Voice is not correct

### ISSUE THREAD

**Issue by lucasjinreal** [rhasspy/piper#84]
Am using command like:

```
.\build\Release\piper.exe -m .\models\en-us-libritts-high.onnx -d out/
```
voice like name it prenouned norm which is weired
[1684593221414818200.zip](https://github.com/rhasspy/piper/files/11522552/1684593221414818200.zip)

**Comment by trunglebka** [comment]
LibriTTS usually contain misaligned audio/text, so models trained on that model can easily "get wrong".
Related: https://github.com/rhasspy/piper/issues/81

**Comment by synesthesiam** [comment]
I'd suggest using the lessac voice for English. It works much better on short sentences.
