### ISSUE TITLE
missing resume training script in python training codes

### ISSUE THREAD

**Issue by 97Cweb** [rhasspy/piper#87]
Checkpoints are saved, and there is code to extract onnx files and test the checkpoint, but no files to resume training from checkpoint

**Comment by StoryHack** [comment]
This is how you would "fiinetune" a new voice from an existing one, isn't it? That would be very useful to know.

**Comment by 97Cweb** [comment]
I was thinking more just being able to start and stop training. Finetune would be good though

**Comment by beqabeqa473** [comment]
just pass --resume_from_checkpoint and a path to checkpoint as an argument when running training

**Comment by 97Cweb** [comment]
Thank you for this! Now I can resume training!
