### ISSUE TITLE
EN: timing issues in speech output with longer text passages

### ISSUE THREAD

**Issue by Cyborgscode** [rhasspy/piper#89]
Source:  Title: The Moon Maid / Author: Edgar Rice Burroughs / Release Date: June 14, 2019 [EBook #59752] / Language: English
Voice: en-us-ryan-high
OS: Fedora 37
Piperrelease: 16.April 2023

if three paragraps from the prologue of the gutenberg ascii version of this text are given to piper, the speechoutput runs at factor 10 or 15 faster and is not understandable, around the last 3 lines it slows down massively, just to read the last line in perfect speed. 

We used paragraphs 7-9  for the test run, ending with "...as the point in the universe occupied by the planet Mars."

if we us use one paragraph, speed it normal. So bug depends on the time a subroutine needs to calculate the entire text.

**Comment by Cyborgscode** [comment]
it's not only a  length issue, as a text short block with a few " ' " and some LFs also triggers this bug.

**Comment by synesthesiam** [comment]
Please try again with Piper v1. It will automatically split into sentences, so it may work better.
