### ISSUE TITLE
Using previous dataset and/or porting .pth from other model?

### ISSUE THREAD

**Issue by RobertAgee** [rhasspy/piper#91]
I've trained my voice with the tortoise tts, but afaik,the pickle file is not compatible with piper, however I still have the dataset I used from previous training. I wonder if there's a way I can either port the .pth or retrain with the audio corpus I already have?

**Comment by synesthesiam** [comment]
You can retrain with the audio corpus. I'd suggest finetuning one of the [pre-trained models](https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main) with `--resume_from_checkpoint`
Surprisingly, this will work well across languages too so you can start with the lessac English voice and get German out, for example.

**Comment by synesthesiam** [comment]
If you're willing/able to share the corpus too, I might be able to train it for you.
