### ISSUE TITLE
checkpoints for french

### ISSUE THREAD

**Issue by meriamOu** [rhasspy/piper#97]
Dear Michael,
thank you so much for the great work! Could you please share the checkpoint for french training. I see french in not available in the link you shared with us:https://drive.google.com/drive/folders/1Hd_dP9BpDYbi1enRDEMIN34W1nfIgmp6
thank you

**Comment by synesthesiam** [comment]
I'm uploading checkpoints here now: https://huggingface.co/datasets/rhasspy/piper-checkpoints/tree/main
